#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Prusa_AIO_Conditionals.h
 * Configuration logic based on Prusa_AIO_Configuration.h options at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define PRUSA_AIO_VERSION 20241019

//===========================================================================
//============================ Source Code Info =============================
//===========================================================================

#define SOURCE_CODE_URL "bit.ly/3FnRN20"
#define WEBSITE_URL SOURCE_CODE_URL

//===========================================================================
//============================== Printer Name ===============================
//===========================================================================

#ifndef PRUSA_AIO_CUSTOM_PRINTER_NAME
  #define PRUSA_AIO_CUSTOM_PRINTER_NAME "AIO Bear"
#endif

//===========================================================================
//=========================== Printer/Frame Type ============================
//===========================================================================

#define PRUSA_AIO_Z_MAX_POS TERN(PRUSA_AIO_FRAME_BEAR_320, 320, 210)

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

// Define MOTHERBOARD here so preflight-checks.py works
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0)
  #define MOTHERBOARD BOARD_BTT_SKR_V3_0
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN FAN2_PIN                             // PB5
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_NEEDS_ALT_DISPLAY_MINI_12864_NEOPIXEL_ORDER 1 // Incorrect RGB color workaround on SKR V3
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 1
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PE6
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ)
  #define MOTHERBOARD BOARD_BTT_SKR_V3_0_EZ
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN FAN2_PIN                             // PB5
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_NEEDS_ALT_DISPLAY_MINI_12864_NEOPIXEL_ORDER 1 // Incorrect RGB color workaround on SKR V3
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 1
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PE6
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
  #define MOTHERBOARD BOARD_BTT_SKR_V2_0_REV_B
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN FAN2_PIN                             // PB5
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 1
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PE6
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4)
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 0
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN P1_24
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO)
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 0
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN P1_24
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3)
  #define MOTHERBOARD BOARD_BTT_SKR_V1_3
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 0
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #define MOTHERBOARD BOARD_BTT_BTT002_V1_0
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD                         // No onboard SD card connection
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define MK3_FAN_PINS                                            // Disable this for FAN_PIN PB9 and FAN1_PIN PB8
  #define NO_MK3_FAN_PINS_WARNING
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 2
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN FAN2_PIN                             // PB15
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 2
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA8
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0_1
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN FAN2_PIN                             // PC8
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 2
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA14
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 2
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA8
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3)
  #define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN HEATER_1_PIN                         // PB0
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // 4-pin header marked "5V GND TX3 RX3"
  #define PRUSA_AIO_WIFI_SERIAL_PORT 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1)
  #define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3_1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN HEATER_1_PIN                         // PB0
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // 4-pin header marked "5V GND TX3 RX3"
  #define PRUSA_AIO_WIFI_SERIAL_PORT 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0)
  #define MOTHERBOARD BOARD_MKS_EAGLE
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN HEATER_1_PIN                         // PB0
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // 4-pin header marked "5V GND TX3 RX3"
  #define PRUSA_AIO_WIFI_SERIAL_PORT 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
  #define MOTHERBOARD BOARD_MKS_SGEN_L_V2
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_HAS_FIVE_DRIVERS 1
  #define PRUSA_AIO_HAS_CONTROLLER_FAN 1
  #define CONTROLLER_FAN_PIN HEATER_1_PIN                         // P2.6
  #define PRUSA_AIO_MEDIA_INIT_WARNING 1                          // Shared SD detect
  #define PRUSA_AIO_SDCARD_CONNECTION LCD
  #define PRUSA_AIO_USB_SERIAL_PORT -1
  #define PRUSA_AIO_TFT_SERIAL_PORT 0
  #define PRUSA_AIO_WIFI_SERIAL_PORT 3
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT 1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // AUX-1
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA2
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3_V1_1
  #define PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT 1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // AUX-1
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA2
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3D
  #define PRUSA_AIO_NO_FAN1_PIN 1
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT 1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // AUX-1
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA2
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3D_V1_1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
  #define PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE 1
  #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD
  #define PRUSA_AIO_NEEDS_FAN_SOFT_PWM 1
  #define PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT 1
  #define PRUSA_AIO_USB_SERIAL_PORT 1
  #define PRUSA_AIO_TFT_SERIAL_PORT 3                             // AUX-1
  #define PRUSA_AIO_BOARD_NEOPIXEL_PIN PA2
#endif

// Remove the need to poll the interrupt pins, saving many CPU cycles
#if ENABLED(PRUSA_AIO_HAS_ENDSTOP_INTERRUPTS_FEATURE)
  #define ENDSTOP_INTERRUPTS_FEATURE
#endif

// Support for USB thumb drives
#if ENABLED(PRUSA_AIO_FLASH_DRIVE_SUPPORT)
  #define USB_FLASH_DRIVE_SUPPORT
#endif

//===========================================================================
//============================== Serial Ports ===============================
//===========================================================================

#if ALL(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_WIFI_SUPPORT)
  #define SERIAL_PORT_2 PRUSA_AIO_TFT_SERIAL_PORT
  #define SERIAL_PORT_3 PRUSA_AIO_WIFI_SERIAL_PORT
#elif ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
  #define SERIAL_PORT_2 PRUSA_AIO_TFT_SERIAL_PORT
#elif ENABLED(PRUSA_AIO_WIFI_SUPPORT)
  #define SERIAL_PORT_2 PRUSA_AIO_WIFI_SERIAL_PORT
#endif

//===========================================================================
//============================= Stepper Drivers =============================
//===========================================================================

#if ENABLED(PRUSA_AIO_HAS_FIVE_DRIVERS)
  #define Z2_DRIVER_TYPE Z_DRIVER_TYPE
#endif

#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #define PRUSA_AIO_DRIVER_TYPE TMC5160
  #define PRUSA_AIO_XY_MIN_ENDSTOP_HIT_STATE TERN(SENSORLESS_HOMING, LOW, HIGH)
  #define TMC_USE_SW_SPI
  #define PRUSA_AIO_DRIVER_RSENSE 0.075
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2130)
  #define PRUSA_AIO_DRIVER_TYPE TMC2130
  #define PRUSA_AIO_XY_MIN_ENDSTOP_HIT_STATE TERN(SENSORLESS_HOMING, LOW, HIGH)
  #define TMC_USE_SW_SPI
  #define PRUSA_AIO_DRIVER_RSENSE 0.11
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE)
  #define PRUSA_AIO_DRIVER_TYPE TMC2209
  #define PRUSA_AIO_XY_MIN_ENDSTOP_HIT_STATE TERN(SENSORLESS_HOMING, HIGH, LOW)
  #define PRUSA_AIO_DRIVER_RSENSE 0.15
#elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE)
  #define PRUSA_AIO_DRIVER_TYPE TMC2209
  #define PRUSA_AIO_XY_MIN_ENDSTOP_HIT_STATE TERN(SENSORLESS_HOMING, HIGH, LOW)
  #define PRUSA_AIO_DRIVER_RSENSE 0.11
#endif

// Silence default driver warnings since they're handled in Prusa_AIO_Warnings.cpp
#define NO_AUTO_ASSIGN_WARNING
#define DIAG_JUMPERS_REMOVED
#define DIAG_PINS_REMOVED

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

/**
 * Motor directions as viewed from the shaft side of the motor
 *
 *                     |  +  |  -  |
 * --------------------|-----|-----|
 * X Motor             | CW  | CCW |
 * Y Motor             | CCW | CW  |
 * Z Motors            | CW  | CCW |
 * E Motor (Stock)     | CCW | CW  |
 * E Motor (BMG)       | CW  | CCW |
 * E Motor (Planetary) | CW  | CCW |
 */

// Default Extruder inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if ENABLED(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT)
    #define INVERT_E0_DIR true
  #else
    #define INVERT_E0_DIR  false
  #endif
#elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC2130)
  #if ANY(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT, PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA)
    #define INVERT_E0_DIR false
  #else
    #define INVERT_E0_DIR true
  #endif
#endif

#if ENABLED(PRUSA_AIO_E_STEPPER_STOCK)
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 280
  #define PRUSA_AIO_E0_CURRENT              550
  #define PRUSA_AIO_E0_MICROSTEPS            32

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_DEFAULT_24V
  #endif
#elif ENABLED(PRUSA_AIO_E_STEPPER_BONDTECH)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 830
  #define PRUSA_AIO_E0_CURRENT              550
  #define PRUSA_AIO_E0_MICROSTEPS            32

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_DEFAULT_24V
  #endif
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_1_8)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 830
  #define PRUSA_AIO_E0_CURRENT              550
  #define PRUSA_AIO_E0_MICROSTEPS            32

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_DEFAULT_24V
  #endif
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_0_9)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 830
  #define PRUSA_AIO_E0_CURRENT              550
  #define PRUSA_AIO_E0_MICROSTEPS            16

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_09STEP_24V
  #endif
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 980
  #define PRUSA_AIO_E0_CURRENT              650
  #define PRUSA_AIO_E0_MICROSTEPS            32

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_DEFAULT_24V
  #endif
#endif

// User Extruder inverting
#if ENABLED(PRUSA_AIO_INVERT_E_DIR)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
#endif

#if ENABLED(PRUSA_AIO_XY_STEPPERS_STOCK)
  #define PRUSA_AIO_DEFAULT_AXIS_STEPS_PER_UNIT  { 100, 100, 400, (PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT) }

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_X CHOPPER_DEFAULT_24V
    #define PRUSA_AIO_CHOPPER_TIMING_Y CHOPPER_DEFAULT_24V
    #define PRUSA_AIO_CHOPPER_TIMING_Z CHOPPER_DEFAULT_24V
  #endif

  #ifndef PRUSA_AIO_X_CURRENT
    #define PRUSA_AIO_X_CURRENT      500
  #endif
  #ifndef PRUSA_AIO_X_CURRENT_HOME
    #define PRUSA_AIO_X_CURRENT_HOME 200
  #endif
  #ifndef PRUSA_AIO_Y_CURRENT
    #define PRUSA_AIO_Y_CURRENT      600
  #endif
  #ifndef PRUSA_AIO_Y_CURRENT_HOME
    #define PRUSA_AIO_Y_CURRENT_HOME 250
  #endif

  // StallGuard settings
  #ifndef PRUSA_AIO_X_STALL_SENSITIVITY
    #if ANY(PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130)
      #define PRUSA_AIO_X_STALL_SENSITIVITY 2
    #elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE)
      #define PRUSA_AIO_X_STALL_SENSITIVITY 90
    #endif
  #endif
  #ifndef PRUSA_AIO_Y_STALL_SENSITIVITY
    #if ANY(PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130)
      #define PRUSA_AIO_Y_STALL_SENSITIVITY 3
    #elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE)
      #define PRUSA_AIO_Y_STALL_SENSITIVITY 100
    #endif
  #endif

#elif ANY(PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
  #define PRUSA_AIO_DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 400, (PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT) }

  #if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
    #define PRUSA_AIO_CHOPPER_TIMING_X CHOPPER_09STEP_24V
    #define PRUSA_AIO_CHOPPER_TIMING_Y CHOPPER_09STEP_24V
    #define PRUSA_AIO_CHOPPER_TIMING_Z CHOPPER_09STEP_24V
  #endif

  #if ENABLED(PRUSA_AIO_XY_STEPPERS_LDO_0_9)
    #ifndef PRUSA_AIO_X_CURRENT
      #define PRUSA_AIO_X_CURRENT      900
    #endif
    #ifndef PRUSA_AIO_X_CURRENT_HOME
      #define PRUSA_AIO_X_CURRENT_HOME 300
    #endif
    #ifndef PRUSA_AIO_Y_CURRENT
      #define PRUSA_AIO_Y_CURRENT     1000
    #endif
    #ifndef PRUSA_AIO_Y_CURRENT_HOME
      #define PRUSA_AIO_Y_CURRENT_HOME 400
    #endif

    // StallGuard settings
    #ifndef PRUSA_AIO_X_STALL_SENSITIVITY
      #define PRUSA_AIO_X_STALL_SENSITIVITY 81
    #endif

    #ifndef PRUSA_AIO_Y_STALL_SENSITIVITY
      #define PRUSA_AIO_Y_STALL_SENSITIVITY 85
    #endif

  #elif ENABLED(PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
    #ifndef PRUSA_AIO_X_CURRENT
      #define PRUSA_AIO_X_CURRENT      650
    #endif
    #ifndef PRUSA_AIO_X_CURRENT_HOME
      #define PRUSA_AIO_X_CURRENT_HOME 225
    #endif
    #ifndef PRUSA_AIO_Y_CURRENT
      #define PRUSA_AIO_Y_CURRENT      750
    #endif
    #ifndef PRUSA_AIO_Y_CURRENT_HOME
      #define PRUSA_AIO_Y_CURRENT_HOME 200
    #endif

    // StallGuard settings
    #ifndef PRUSA_AIO_X_STALL_SENSITIVITY
      #define PRUSA_AIO_X_STALL_SENSITIVITY 140
    #endif
    #ifndef PRUSA_AIO_Y_STALL_SENSITIVITY
      #define PRUSA_AIO_Y_STALL_SENSITIVITY 132
    #endif
  #endif
#endif

// MK2.5S is 12V
#if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
  #define PRUSA_AIO_CHOPPER_TIMING_X CHOPPER_DEFAULT_12V
  #define PRUSA_AIO_CHOPPER_TIMING_Y CHOPPER_DEFAULT_12V
  #define PRUSA_AIO_CHOPPER_TIMING_Z CHOPPER_DEFAULT_12V
  #define PRUSA_AIO_CHOPPER_TIMING_E CHOPPER_DEFAULT_12V
#endif

// Homing speeds (mm/min)
#ifndef PRUSA_AIO_HOMING_FEEDRATE_MM_M
  #define PRUSA_AIO_HOMING_FEEDRATE_MM_M { (50*60), (50*60), (4*60) }
#endif

// Easier sensorless homing tuning
#if DISABLED(PRUSA_AIO_MK25S_SUPPORT)
  #define EDITABLE_HOMING_FEEDRATE
#endif

// Default X/Y inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if ENABLED(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT)
    #define INVERT_X_DIR false
    #define INVERT_Y_DIR  true
  #else
    #define INVERT_X_DIR  true
    #define INVERT_Y_DIR false
  #endif
#elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC2130)
  #if ENABLED(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT)
    #define INVERT_X_DIR  true
    #define INVERT_Y_DIR false
  #else
    #define INVERT_X_DIR false
    #define INVERT_Y_DIR  true
  #endif
#endif

// Default Z inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if ENABLED(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT)
    #define INVERT_Z_DIR false
  #else
    #define INVERT_Z_DIR  true
  #endif
#elif ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC2130)
  #if ENABLED(PRUSA_AIO_INVERTED_MOTOR_DIR_DEFAULT)
    #define INVERT_Z_DIR  true
  #else
    #define INVERT_Z_DIR false
  #endif
#endif

// User X inverting
#if ENABLED(PRUSA_AIO_INVERT_X_DIR)
  #if INVERT_X_DIR == true
    #undef INVERT_X_DIR // Prevent redefined warnings
    #define INVERT_X_DIR false
  #elif INVERT_X_DIR == false
    #undef INVERT_X_DIR // Prevent redefined warnings
    #define INVERT_X_DIR true
  #endif
#endif

// User Y inverting
#if ENABLED(PRUSA_AIO_INVERT_Y_DIR)
  #if INVERT_Y_DIR == true
    #undef INVERT_Y_DIR // Prevent redefined warnings
    #define INVERT_Y_DIR false
  #elif INVERT_Y_DIR == false
    #undef INVERT_Y_DIR // Prevent redefined warnings
    #define INVERT_Y_DIR true
  #endif
#endif

// User Z inverting
#if ENABLED(PRUSA_AIO_INVERT_Z_DIR)
  #if INVERT_Z_DIR == true
    #undef INVERT_Z_DIR // Prevent redefined warnings
    #define INVERT_Z_DIR false
  #elif INVERT_Z_DIR == false
    #undef INVERT_Z_DIR // Prevent redefined warnings
    #define INVERT_Z_DIR true
  #endif
#endif

//===========================================================================
//================================== Probe ==================================
//===========================================================================

// TODO: E3D Hemera   Note: Shift bed to the left 11mm // X_MIN_POS -11   Y_MIN_POS -2

// Probe Temperature Compensation based on bed temperature
#define PTC_BED

#if ANY(PRUSA_AIO_PROBE_BLTOUCH)
  #define BLTOUCH
  #define PRUSA_AIO_TEMP_SENSOR_PROBE          0
  #define PRUSA_AIO_PROBING_MARGIN             5
  #define PRUSA_AIO_Z_CLEARANCE_DEPLOY_PROBE   5
  #define PRUSA_AIO_Z_CLEARANCE_BETWEEN_PROBES 3
  #define PRUSA_AIO_Z_CLEARANCE_MULTI_PROBE    3

  #ifndef PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
    #if ENABLED(PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH)
      #define PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET { 26.71, 2.298, 0 } // Offsets pulled from https://www.thingiverse.com/thing:3251530/comments#comment-2915938
    #elif ENABLED(PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
      #define PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET { -24.3, -34.1, 0 } // Offsets pulled from https://www.thingiverse.com/thing:3864666/comments#comment-2882122
    #endif
  #endif

#elif ANY(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2)
  #define FIX_MOUNTED_PROBE
  #define PRUSA_AIO_PROBING_MARGIN             10
  #define PRUSA_AIO_Z_CLEARANCE_DEPLOY_PROBE    0
  #define PRUSA_AIO_Z_CLEARANCE_BETWEEN_PROBES  2
  #define PRUSA_AIO_Z_CLEARANCE_MULTI_PROBE     2
  #define PROBING_HEATERS_OFF
  #define Z_STEPPER_ALIGN_XY { { 40, 90 }, { 230, 90 } }

  #ifndef PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
    #define PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET { 23, 5, 0 }
  #endif

  // Probe Temperature Compensation
  #if ENABLED(PRUSA_AIO_PROBE_SUPERPINDA)
    #define PRUSA_AIO_TEMP_SENSOR_PROBE 0
  #elif ENABLED(PRUSA_AIO_PROBE_PINDA_V2)
    #define PRUSA_AIO_TEMP_SENSOR_PROBE 1
    #define PTC_PROBE    // Compensate based on probe temperature
  #endif
#endif

// Use Z endstop pin instead of dedicated probe pin
#if ENABLED(PRUSA_AIO_PROBE_USES_Z_MIN_ENDSTOP_PIN)
  #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#if ENABLED(PRUSA_AIO_THERMISTOR_SEMITEC_104NT)
  #define PRUSA_AIO_TEMP_SENSOR_0      5
  #define PRUSA_AIO_HEATER_0_MINTEMP   5
  #define PRUSA_AIO_HEATER_0_MAXTEMP 310 // 295 + 15 overshoot
#elif ENABLED(PRUSA_AIO_THERMISTOR_GENERIC_100K)
  #define PRUSA_AIO_TEMP_SENSOR_0      1
  #define PRUSA_AIO_HEATER_0_MINTEMP   5
  #define PRUSA_AIO_HEATER_0_MAXTEMP 305 // 290 + 15 overshoot
#elif ENABLED(PRUSA_AIO_THERMISTOR_SLICE_450C)
  #define PRUSA_AIO_TEMP_SENSOR_0     67
  #define PRUSA_AIO_HEATER_0_MINTEMP   5
  #define PRUSA_AIO_HEATER_0_MAXTEMP 465 // 450 + 15 overshoot
#elif ENABLED(PRUSA_AIO_THERMISTOR_TL_T_D500)
  #define PRUSA_AIO_TEMP_SENSOR_0     66
  #define PRUSA_AIO_HEATER_0_MINTEMP  21
  #define PRUSA_AIO_HEATER_0_MAXTEMP 515 // 500 + 15 overshoot
  #define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 5
  #define PREHEAT_TIME_HOTEND_MS 30000
#endif

#if ENABLED(PRUSA_AIO_HOTEND_MPCTEMP)
  #define MPCTEMP

  #if DISABLED(PRUSA_AIO_CUSTOM_HOTEND_MPCTEMP)
    #define PRUSA_AIO_CUSTOM_MPC_HEATER_POWER                { 40.0f }
    #define PRUSA_AIO_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM  { 5.6e-3f } // PLA

    #if ANY(PRUSA_AIO_HOTEND_E3D_REVO_MICRO, PRUSA_AIO_HOTEND_E3D_REVO_SIX)
      #define PRUSA_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY       { 6.02f }
      #define PRUSA_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS     { 0.4224f }
      #define PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF        { 0.0405f }
      #define PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 { 0.0786f }
    #else
      #define PRUSA_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY       { 16.7f }
      #define PRUSA_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS     { 0.22f }
      #define PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF        { 0.068f }
      #define PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 { 0.097f }
    #endif
  #endif
#else
  #define PIDTEMP

  #if DISABLED(PRUSA_AIO_CUSTOM_HOTEND_PID)
    #if ENABLED(PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
      #define PRUSA_AIO_DEFAULT_Kp  16.39
      #define PRUSA_AIO_DEFAULT_Ki   1.55
      #define PRUSA_AIO_DEFAULT_Kd  43.28
    #elif ANY(PRUSA_AIO_HOTEND_E3D_REVO_MICRO, PRUSA_AIO_HOTEND_E3D_REVO_SIX)
      #define PRUSA_AIO_DEFAULT_Kp   25.00  //  20.4  //  40.587
      #define PRUSA_AIO_DEFAULT_Ki    4.8   //   3.99 //   4.163
      #define PRUSA_AIO_DEFAULT_Kd   32.60  //  26.1  //  98.932
    #else
      #define PRUSA_AIO_DEFAULT_Kp  16.50
      #define PRUSA_AIO_DEFAULT_Ki   1.16
      #define PRUSA_AIO_DEFAULT_Kd  58.80
    #endif
  #endif
#endif

#if DISABLED(PRUSA_AIO_CUSTOM_BED_PID)
  #define PRUSA_AIO_DEFAULT_bedKp   28.13
  #define PRUSA_AIO_DEFAULT_bedKi    2.09
  #define PRUSA_AIO_DEFAULT_bedKd  483.07
#endif

//===========================================================================
//================================== Fans ===================================
//===========================================================================

// Hotend Cooling Fan
// PIN_EXISTS() macro doesn't work here
#define PRUSA_AIO_E0_AUTO_FAN_PIN TERN(PRUSA_AIO_NO_FAN1_PIN, -1, FAN1_PIN)

#if ENABLED(PRUSA_AIO_NEEDS_FAN_SOFT_PWM)
  #define FAN_SOFT_PWM
  #define PRUSA_AIO_SOFT_PWM_SCALE 1 // :[0,1,2,3,4,5,6,7]
  #define SOFT_PWM_DITHER
#else
  #define PRUSA_AIO_SOFT_PWM_SCALE 0
#endif

// Part Cooling Fan
//TODO: Test all fan/board combos
#if ENABLED(PRUSA_AIO_PART_COOLING_FAN_GENERIC)
  #define PRUSA_AIO_FAN_MIN_PWM 0
#elif ANY(PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_12V_STOCK_PRUSA_MK25S_5015, PRUSA_AIO_PART_COOLING_FAN_12V_SOUNDORIGINAL)
  #if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
    #define PRUSA_AIO_FAN_MIN_PWM 40
  #elif ANY(PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3)
    #define PRUSA_AIO_FAN_MIN_PWM 115
  #elif ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define PRUSA_AIO_FAN_MIN_PWM 50
  #else
    #define PRUSA_AIO_FAN_MIN_PWM 80
  #endif
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH)
  #define PRUSA_AIO_FAN_MIN_PWM 20
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #define PRUSA_AIO_FAN_MIN_PWM 51
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015)
  #define PRUSA_AIO_FAN_MIN_PWM 0 // TODO: Find correct value
#endif

// Controller/Motherboard Fan
#if ENABLED(PRUSA_AIO_MOTHERBOARD_FAN) && DISABLED(PRUSA_AIO_HAS_CONTROLLER_FAN)
  #error "PRUSA_AIO_MOTHERBOARD_FAN is not compatible with enabled motherboard. Connect motherboard cooling fan directly to 24V power supply."
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_FAN)
  #define USE_CONTROLLER_FAN

  // Keep Controller fan active for 2130s
  #if DISABLED(PRUSA_AIO_DRIVERS_TMC2130)
    #define CONTROLLER_FAN_IGNORE_Z
  #endif
#endif

//===========================================================================
//======================= Bed Leveling / Calibration =======================
//===========================================================================

#if ENABLED(PRUSA_AIO_BED_LEVELING_BILINEAR)
  #define AUTO_BED_LEVELING_BILINEAR
  #define G29_RETRY_AND_RECOVER
#elif ENABLED(PRUSA_AIO_BED_LEVELING_UBL)
  #define AUTO_BED_LEVELING_UBL
#endif

#if ENABLED(PRUSA_AIO_HAS_FIVE_DRIVERS)
  #define Z_STEPPER_AUTO_ALIGN
#else // Single Z driver
  #define MECHANICAL_GANTRY_CALIBRATION
#endif

//===========================================================================
//============================== Custom Menus ===============================
//===========================================================================

// Sheet Profiles Menu
#if ENABLED(PRUSA_AIO_SHEET_PROFILES_MENU)
  #define CUSTOM_MENU_CONFIG

  #if defined(PRUSA_AIO_SHEET_1_DESC) && defined(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_DESC PRUSA_AIO_SHEET_1_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_2_DESC) && defined(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_DESC PRUSA_AIO_SHEET_2_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_3_DESC) && defined(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_DESC PRUSA_AIO_SHEET_3_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_4_DESC) && defined(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_DESC PRUSA_AIO_SHEET_4_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_5_DESC) && defined(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_DESC PRUSA_AIO_SHEET_5_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_6_DESC) && defined(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_DESC PRUSA_AIO_SHEET_6_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_7_DESC) && defined(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_DESC PRUSA_AIO_SHEET_7_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_8_DESC) && defined(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_DESC PRUSA_AIO_SHEET_8_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_9_DESC) && defined(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_DESC PRUSA_AIO_SHEET_9_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_10_DESC) && defined(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_DESC PRUSA_AIO_SHEET_10_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_CONFIRM
  #endif
#endif

// Calibration Menu
#if ENABLED(PRUSA_AIO_CALIBRATION_MENU)
  #define CUSTOM_MENU_MAIN
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if ANY(PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL)
  #define PRUSA_AIO_HAS_MINI_12864_NEOPIXEL 1
  #define PRUSA_AIO_LCD_NEOPIXEL EXP1_06_PIN
  #define PRUSA_AIO_LCD_NEOPIXEL_COUNT 3
#elif ANY(PRUSA_AIO_DISPLAY_BTT_TFT35_SPI_V1, PRUSA_AIO_DISPLAY_MKS_TS35_V2_0)
  #define PRUSA_AIO_HAS_SPI_TFT 1
#endif

#if ANY(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER)
  #define REPRAP_DISCOUNT_SMART_CONTROLLER
#elif ANY(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_HAS_MINI_12864_NEOPIXEL, PRUSA_AIO_HAS_SPI_TFT)
  #if ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)

    // Extra defines for BTT TFT firmware
    #define AUTO_REPORT_POSITION
    #define AUTO_REPORT_SD_STATUS
    #define SERIAL_FLOAT_PRECISION 4

    #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
      #define CR10_STOCKDISPLAY
      #define PRUSA_AIO_SINGLE_EXP_CONNECTION 1
    #else
      #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
    #endif
  #elif ENABLED(PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL)
    #define BTT_MINI_12864
  #elif ENABLED(PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL)
    #define PRUSA_AIO_REVERSE_ENCODER_DIRECTION_DEFAULT
    #define FYSETC_MINI_12864_2_1
    //#define ENCODER_PULSES_PER_STEP 3
  #elif ENABLED(PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL)
    #define MKS_MINI_12864_V3
  #elif ENABLED(PRUSA_AIO_HAS_SPI_TFT)
    #define TFT_COLOR_UI
    #define TOUCH_SCREEN

    #define ENCODER_PULSES_PER_STEP 6

    #undef PRUSA_AIO_SDCARD_CONNECTION
    #define PRUSA_AIO_SDCARD_CONNECTION ONBOARD  // No SD card reader on TFT

    #if ENABLED(PRUSA_AIO_DISPLAY_BTT_TFT35_SPI_V1)
      #define BTT_TFT35_SPI_V1_0
      #define TFT_DRIVER ST7796
    #elif ENABLED(PRUSA_AIO_DISPLAY_MKS_TS35_V2_0)
      #define MKS_TS35_V2_0
    #endif
  #endif

  #if ENABLED(PRUSA_AIO_BED_LEVELING_UBL) && NONE(TFT_COLOR_UI, TFT_LVGL_UI)
    #define MESH_EDIT_GFX_OVERLAY
  #endif

  #if NONE(TFT_COLOR_UI, TFT_LVGL_UI)
    #define BABYSTEP_GFX_OVERLAY
  #endif
#endif

// Final encoder direction
#if (ENABLED(PRUSA_AIO_REVERSE_ENCODER_DIRECTION_DEFAULT) && DISABLED(PRUSA_AIO_REVERSE_ENCODER_DIRECTION)) || (ENABLED(PRUSA_AIO_REVERSE_ENCODER_DIRECTION) && DISABLED(PRUSA_AIO_REVERSE_ENCODER_DIRECTION_DEFAULT))
  #define REVERSE_ENCODER_DIRECTION
#endif

// Suppress potential LCD contrast warning
#define NO_LCD_CONTRAST_WARNING

//===========================================================================
//================================ NeoPixels ================================
//===========================================================================

#if ANY(PRUSA_AIO_NEOPIXEL_STRIP, PRUSA_AIO_HAS_MINI_12864_NEOPIXEL)
  #define NEOPIXEL_LED // Enable NeoPixel support
  #define LED_CONTROL_MENU
  #define LED_COLOR_PRESETS
  #define NEOPIXEL_STARTUP_TEST
#endif

#if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP) // Both NeoPixel Strip & Mini 12864 w/ NeoPixels / Dual NeoPixel workaround
  #define NEOPIXEL_PIN PRUSA_AIO_BOARD_NEOPIXEL_PIN

  #define NEOPIXEL_TYPE PRUSA_AIO_NEOPIXEL_STRIP_TYPE
  #define NEOPIXEL_PIXELS PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT
  #define NEOPIXEL_BRIGHTNESS PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS

  #if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN       25
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN       75
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #endif

  #if ENABLED(PRUSA_AIO_HAS_MINI_12864_NEOPIXEL)
    #define NEOPIXEL2_SEPARATE
    #define NEO2_COLOR_PRESETS

    // Incorrect RGB color workaround on SKR V3
    #define NEOPIXEL2_TYPE TERN(PRUSA_AIO_NEEDS_ALT_DISPLAY_MINI_12864_NEOPIXEL_ORDER, NEO_BRG, NEO_RGB)
    #define NEOPIXEL2_PIN PRUSA_AIO_LCD_NEOPIXEL

    #define NEOPIXEL2_PIXELS PRUSA_AIO_LCD_NEOPIXEL_COUNT
    #define NEOPIXEL2_BRIGHTNESS 255

    #if ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED        255
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN        0
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE         0
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED        255
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN       25
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE         0
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED        255
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN       75
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE         0
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED          0
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN      255
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE         0
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED          0
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN        0
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE       255
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED          0
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN      255
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE       255
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED        255
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN        0
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE       255
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
      #define PRUSA_AIO_NEO2_USER_PRESET_RED        255
      #define PRUSA_AIO_NEO2_USER_PRESET_GREEN      255
      #define PRUSA_AIO_NEO2_USER_PRESET_BLUE       255
      #define PRUSA_AIO_NEO2_USER_PRESET_WHITE      255
    #endif
  #endif
#elif ENABLED(PRUSA_AIO_HAS_MINI_12864_NEOPIXEL) // Only Mini 12864 w/ NeoPixels
  // Incorrect RGB color workaround on SKR V3
  #define NEOPIXEL_TYPE TERN(PRUSA_AIO_NEEDS_ALT_DISPLAY_MINI_12864_NEOPIXEL_ORDER, NEO_BRG, NEO_RGB)

  #define NEOPIXEL_PIXELS PRUSA_AIO_LCD_NEOPIXEL_COUNT
  #define NEOPIXEL_BRIGHTNESS 255

  #define LED_USER_PRESET_STARTUP
  #define NEOPIXEL_PIN PRUSA_AIO_LCD_NEOPIXEL

  #if ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN       25
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN       75
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE         0
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO)
    #define PRUSA_AIO_LED_USER_PRESET_RED          0
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN        0
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #define PRUSA_AIO_LED_USER_PRESET_RED        255
    #define PRUSA_AIO_LED_USER_PRESET_GREEN      255
    #define PRUSA_AIO_LED_USER_PRESET_BLUE       255
    #define PRUSA_AIO_LED_USER_PRESET_WHITE      255
  #endif
#endif

//===========================================================================
//=============================  Input Shaping ==============================
//===========================================================================

#if ENABLED(PRUSA_AIO_INPUT_SHAPING)
  #define INPUT_SHAPING_X
  #define INPUT_SHAPING_Y
  #ifdef PRUSA_AIO_SHAPING_MIN_FREQ
    #define SHAPING_MIN_FREQ PRUSA_AIO_SHAPING_MIN_FREQ
  #endif
  #ifdef PRUSA_AIO_SHAPING_MAX_STEPRATE
    #define SHAPING_MAX_STEPRATE PRUSA_AIO_SHAPING_MAX_STEPRATE
  #endif
#else
  #define S_CURVE_ACCELERATION // Not needed/recommended with Input Shaping
#endif
