#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

#define CONFIGURATION_H_VERSION 02010100
#define PRUSA_AIO_VERSION 20220807

//===========================================================================
//=========================== Printer/Frame Type ============================
//===========================================================================

#if BOTH(PRUSA_AIO_FRAME_BEAR_210, PRUSA_AIO_FRAME_BEAR_320)
  #error "Only one PRUSA_AIO_FRAME option can be enabled at a time."
#elif NONE(PRUSA_AIO_FRAME_BEAR_210, PRUSA_AIO_FRAME_BEAR_320)
  #error "Invalid PRUSA_AIO_FRAME option."
#endif

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

#if MANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #error "Only one PRUSA_AIO_MOTHERBOARD option can be enabled at a time."
#elif NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #error "Invalid PRUSA_AIO_MOTHERBOARD option."
#endif

// BTT002 Sanity Checks
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #if EITHER(PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH) // No Servo Pins on BTT002
    #error "BLTouch is not supported on BigTreeTech BTT002 1.0."
  #endif

  #if ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
    #error "BigTreeTech Dual Mode TFTs emulate the SD card reader and cannot be used for motherboard firmware updates. Since the BigTreeTech BTT002 1.0 has no onboard SD card reader, a different display type is required."
  #endif
#endif

// PINDA V2 Sanity Checks
#if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1) && ENABLED(PRUSA_AIO_PROBE_PINDA_V2)
  #error "PINDA V2 is not supported on enabled motherboard. A SuperPINDA or BLTouch is required."
#endif

// Flash Drive Support (BigTreeTech SKR 2 & MKS Robin Nano V3 only)
#if ENABLED(PRUSA_AIO_FLASH_DRIVE_SUPPORT) && NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3)
  #error "PRUSA_AIO_FLASH_DRIVE_SUPPORT is not compatible with enabled motherboard."
#endif

//===========================================================================
//============================= Stepper Drivers =============================
//===========================================================================

#if BOTH(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC5160)
  #error "Only one PRUSA_AIO_DRIVERS option can be enabled at a time."
#elif NONE(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC5160)
  #error "Invalid PRUSA_AIO_DRIVERS option."
#endif

// Integrated TMC2209s Sanity Checks
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160) && ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1)
  #error "Invalid PRUSA_AIO_DRIVERS option. Enabled motherboard has onboard TMC2209s."
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

#if MANY(PRUSA_AIO_E_STEPPER_STOCK, PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH, PRUSA_AIO_E_STEPPER_LDO_0_9, PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #error "Only one PRUSA_AIO_E_STEPPER option can be enabled at a time."
#elif NONE(PRUSA_AIO_E_STEPPER_STOCK, PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH, PRUSA_AIO_E_STEPPER_LDO_0_9, PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #error "Invalid PRUSA_AIO_E_STEPPER option."
#endif

#if EITHER(PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH, PRUSA_AIO_E_STEPPER_LDO_0_9) && EITHER(PRUSA_AIO_EXTRUDER_BEAR_PINDA, PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH)
  // Not powerful enough to drive 1:1 extruders
  #error "Pancake stepper on a Bear extruder is not supported."
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_PLANETARY) && EITHER(PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
  // This would be a crazy amount of pulses/second
  #error "Planetary stepper on a BMG extruder is not supported."
#endif

#if MANY(PRUSA_AIO_XY_STEPPERS_STOCK, PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
	#error "Only one PRUSA_AIO_XY_STEPPERS option can be enabled at a time."
#elif NONE(PRUSA_AIO_XY_STEPPERS_STOCK, PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
	#error "Invalid PRUSA_AIO_XY_STEPPERS option."
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

#if MANY(PRUSA_AIO_EXTRUDER_BEAR_PINDA, PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
	#error "Only one PRUSA_AIO_EXTRUDER option can be enabled at a time."
#elif NONE(PRUSA_AIO_EXTRUDER_BEAR_PINDA, PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
	#error "Invalid PRUSA_AIO_EXTRUDER option."
#endif

#if EITHER(PRUSA_AIO_EXTRUDER_BEAR_PINDA, PRUSA_AIO_EXTRUDER_BMG_PINDA)
  #if BOTH(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2)
    #error "Only one PRUSA_AIO_PROBE option can be enabled at a time."
  #elif NONE(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2)
    #error "Invalid PRUSA_AIO_PROBE option."
  #endif
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#if MANY(PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT, PRUSA_AIO_THERMISTOR_GENERIC_100K, PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_DYZE_DESIGN)
	#error "Only one PRUSA_AIO_THERMISTOR option can be enabled at a time."
#elif NONE(PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT, PRUSA_AIO_THERMISTOR_GENERIC_100K, PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_DYZE_DESIGN)
	#error "Invalid PRUSA_AIO_THERMISTOR option."
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_HOTEND_PID) && (!defined(PRUSA_AIO_DEFAULT_Kp) || !defined(PRUSA_AIO_DEFAULT_Ki) || !defined(PRUSA_AIO_DEFAULT_Kd))
  #error "PRUSA_AIO_DEFAULT_Kp, PRUSA_AIO_DEFAULT_Ki, or PRUSA_AIO_DEFAULT_Kd are invalid or not defined."
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_BED_PID) && (!defined(PRUSA_AIO_DEFAULT_bedKp) || !defined(PRUSA_AIO_DEFAULT_bedKi) || !defined(PRUSA_AIO_DEFAULT_bedKd))
  #error "PRUSA_AIO_DEFAULT_bedKp, PRUSA_AIO_DEFAULT_bedKi, or PRUSA_AIO_DEFAULT_bedKd are invalid or not defined."
#endif

//===========================================================================
//============================ Part Cooling Fan =============================
//===========================================================================

#if MANY(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
	#error "Only one PRUSA_AIO_PART_COOLING_FAN option can be enabled at a time."
#elif NONE(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
	#error "Invalid PRUSA_AIO_PART_COOLING_FAN option."
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002) && NONE(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option. 24V fans are not supported on BigTreeTech BTT002 1.0."
#elif DISABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002) && EITHER(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option. 5V fans are for BigTreeTech BTT002 1.0 only."
#endif

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

#if BOTH(PRUSA_AIO_BED_LEVELING_BILINEAR, PRUSA_AIO_BED_LEVELING_UBL)
	#error "Only one PRUSA_AIO_BED_LEVELING option can be enabled at a time."
#elif NONE(PRUSA_AIO_BED_LEVELING_BILINEAR, PRUSA_AIO_BED_LEVELING_UBL)
	#error "Invalid PRUSA_AIO_BED_LEVELING option."
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if MANY(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #error "Only one PRUSA_AIO_DISPLAY option can be enabled at a time."
#elif NONE(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #error "Invalid PRUSA_AIO_DISPLAY option."
#elif ENABLED(PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER) && ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #error "OLED RepRapDiscount smart controller is only compatible with LPC-based motherboards."
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3) && ANY(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #error "Invalid PRUSA_AIO_DISPLAY option. SKR Mini E3 V3 has a single EXP connector and is only compatible with PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT."
#endif

#if ENABLED(PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #if MANY(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED, PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW, PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN, PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO, PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET, PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #error "Only one PRUSA_AIO_LCD_NEOPIXEL_COLOR option can be enabled at a time."
  #elif NONE(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED, PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW, PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN, PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO, PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET, PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #error "Invalid PRUSA_AIO_LCD_NEOPIXEL_COLOR option."
  #endif
#endif

#if !defined(PRUSA_AIO_LCD_LANGUAGE)
  #error "Invalid PRUSA_AIO_LCD_LANGUAGE option."
#endif

//===========================================================================
//============================= NeoPixel Strip ==============================
//===========================================================================

#if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP)

  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3)
    #error "NeoPixels are not compatible with enabled motherboard."
  #endif

  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_TYPE
    #error "Invalid PRUSA_AIO_NEOPIXEL_STRIP_TYPE option."
  #endif

  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT
    #error "Invalid PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT option."
  #endif

  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS
    #error "Invalid PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS option."
  #endif

  #if MANY(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #error "Only one PRUSA_AIO_NEOPIXEL_STRIP_COLOR option can be enabled at a time."
  #elif NONE(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #error "Invalid PRUSA_AIO_NEOPIXEL_STRIP_COLOR option."
  #endif
#endif

//===========================================================================
//================================= Renames =================================
//===========================================================================

#ifdef PRUSA_AIO_PRINTER_NAME
  #error "PRUSA_AIO_PRINTER_NAME is now PRUSA_AIO_CUSTOM_PRINTER_NAME. Please update your config."
#endif
