#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Prusa_AIO_Changes.h
 * Alert about Prusa_AIO_Configuration.h changes at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define PRUSA_AIO_VERSION 20241019

#ifdef PRUSA_AIO_PRINTER_NAME
  #error "PRUSA_AIO_PRINTER_NAME is now PRUSA_AIO_CUSTOM_PRINTER_NAME. Please update your config."
#elif defined(PRUSA_AIO_FRAME_BEAR_210)
  #error "PRUSA_AIO_FRAME_BEAR_210 is no longer used and 210mm Z is assumed by default. Please update your config."
#elif defined(PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH)
  #error "PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH is now PRUSA_AIO_E_STEPPER_BONDTECH. Please update your config."
#elif defined(PRUSA_AIO_THERMISTOR_DYZE_DESIGN)
  #error "PRUSA_AIO_THERMISTOR_DYZE_DESIGN is now PRUSA_AIO_THERMISTOR_TL_T_D500. Please update your config."
#elif defined(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)
  #error "PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3 is now PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0. Please update your config."
#elif defined(PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #error "PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL is now PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL, or PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL. Please update your config."
#elif defined(PRUSA_AIO_DRIVERS_BTT_TMC2226)
  #error "PRUSA_AIO_DRIVERS_BTT_TMC2226 is now PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE. Please update your config."
#elif defined(PRUSA_AIO_DRIVERS_MKS_TMC2226)
  #error "PRUSA_AIO_DRIVERS_MKS_TMC2226 is now PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE. Please update your config."
#elif defined(PRUSA_AIO_FT_MOTION)
  #error "PRUSA_AIO_FT_MOTION has been removed to simplify Prusa AIO configuration. Please update your config. To use Fixed-time-based Motion Control, enable FT_MOTION in Configuration_adv.h."
#elif defined(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015)
  #error "PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015 is now PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015. Please update your config."
#elif defined(PRUSA_AIO_EXTRUDER_BEAR_PINDA)
  #error "PRUSA_AIO_EXTRUDER_BEAR_PINDA is now PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA. Please update your config."
#elif defined(PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH)
  #error "PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH is now PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH. Please update your config."
#elif defined(PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT)
  #error "PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT is now PRUSA_AIO_THERMISTOR_SEMITEC_104NT. Please update your config."
#endif
