#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Prusa_AIO_SanityCheck.h
 * Validate Prusa_AIO_Configuration.h options at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define PRUSA_AIO_VERSION 20241019

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

#if MANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #error "Only one PRUSA_AIO_MOTHERBOARD option can be enabled at a time."
#elif NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #error "Invalid PRUSA_AIO_MOTHERBOARD option."
#endif

// BTT002 Sanity Checks
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #if ANY(PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH) // No Servo Pins on BTT002
    #error "BLTouch is not supported on BigTreeTech BTT002 1.0."
  #endif

  #if ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
    #error "BigTreeTech Dual Mode TFTs emulate the SD card reader and cannot be used for motherboard firmware updates. Since the BigTreeTech BTT002 1.0 has no onboard SD card reader, a different display type is required."
  #endif

  // BTT002 is slow and/or locks up with Mini 12864 with NeoPixel RGB
  #if ENABLED(PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL)
    #error "PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL is not supported on BigTreeTech BTT002 1.0."
  #elif ENABLED(PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL)
    #error "PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL is not supported on BigTreeTech BTT002 1.0."
  #elif ENABLED(PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL)
    #error "PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL is not supported on BigTreeTech BTT002 1.0."
  #endif
#endif // BTT002 Sanity Checks

// Flash Drive Support (BigTreeTech SKR 2 & MKS Robin Nano V3 only)
#if ENABLED(PRUSA_AIO_FLASH_DRIVE_SUPPORT)
  #if NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0)
    #error "PRUSA_AIO_FLASH_DRIVE_SUPPORT is not compatible with enabled motherboard."
  #elif ALL(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_WIFI_SUPPORT)
    #error "Both PRUSA_AIO_FLASH_DRIVE_SUPPORT and PRUSA_AIO_WIFI_SUPPORT cannot be enabled at the same time for PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B."
  #endif
#endif

// WiFi Support
#if ENABLED(PRUSA_AIO_WIFI_SUPPORT) && NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
  #error "Enabled motherboard does not have WiFi support."
#endif

//===========================================================================
//============================= Stepper Drivers =============================
//===========================================================================

#if MANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130)
  #error "Only one PRUSA_AIO_DRIVERS option can be enabled at a time."
#elif NONE(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE, PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130)
  #error "Invalid PRUSA_AIO_DRIVERS option."
#endif

// Integrated TMC2209s Sanity Checks
#if DISABLED(PRUSA_AIO_DRIVERS_TMC2209) && ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0)
  #error "Invalid PRUSA_AIO_DRIVERS option. Enabled motherboard has integrated TMC2209s."
#endif

//===========================================================================
//=========================== Endstops/StallGuard ===========================
//===========================================================================

#if ENABLED(PRUSA_AIO_MK25S_SUPPORT) && (defined(PRUSA_AIO_X_STALL_SENSITIVITY) || defined(PRUSA_AIO_Y_STALL_SENSITIVITY))
  #error "PRUSA_AIO_MK25S_SUPPORT homes X & Y with endstops and is not compatible with PRUSA_AIO_X_STALL_SENSITIVITY / PRUSA_AIO_Y_STALL_SENSITIVITY."
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

#if MANY(PRUSA_AIO_E_STEPPER_STOCK, PRUSA_AIO_E_STEPPER_BONDTECH, PRUSA_AIO_E_STEPPER_LDO_1_8, PRUSA_AIO_E_STEPPER_LDO_0_9, PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #error "Only one PRUSA_AIO_E_STEPPER option can be enabled at a time."
#elif NONE(PRUSA_AIO_E_STEPPER_STOCK, PRUSA_AIO_E_STEPPER_BONDTECH, PRUSA_AIO_E_STEPPER_LDO_1_8, PRUSA_AIO_E_STEPPER_LDO_0_9, PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #error "Invalid PRUSA_AIO_E_STEPPER option."
#endif

#if ANY(PRUSA_AIO_E_STEPPER_BONDTECH, PRUSA_AIO_E_STEPPER_LDO_1_8, PRUSA_AIO_E_STEPPER_LDO_0_9) && ANY(PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH)
  // Not powerful enough to drive 1:1 extruders
  #error "Pancake stepper is not supported on Bear Extruder V1."
#elif NONE(PRUSA_AIO_E_STEPPER_BONDTECH, PRUSA_AIO_E_STEPPER_LDO_1_8, PRUSA_AIO_E_STEPPER_LDO_0_9) && ENABLED(PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA)
  // BMG extruders should use pancake steppers
  #error "Bear Extruder V2 requires PRUSA_AIO_E_STEPPER_BONDTECH, PRUSA_AIO_E_STEPPER_LDO_1_8, or PRUSA_AIO_E_STEPPER_LDO_0_9 extruder stepper motor."
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_PLANETARY) && ANY(PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH, PRUSA_AIO_EXTRUDER_SFP_PINDA)
  // This would be a crazy number of pulses/second
  #error "Planetary stepper on a BMG extruder is not supported."
#endif

#if MANY(PRUSA_AIO_XY_STEPPERS_STOCK, PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
  #error "Only one PRUSA_AIO_XY_STEPPERS option can be enabled at a time."
#elif NONE(PRUSA_AIO_XY_STEPPERS_STOCK, PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
  #error "Invalid PRUSA_AIO_XY_STEPPERS option."
#endif

//===========================================================================
//================================ Extruder =================================
//===========================================================================

#if MANY(PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH, PRUSA_AIO_EXTRUDER_SFP_PINDA)
  #error "Only one PRUSA_AIO_EXTRUDER option can be enabled at a time."
#elif NONE(PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH, PRUSA_AIO_EXTRUDER_SFP_PINDA)
  #error "Invalid PRUSA_AIO_EXTRUDER option."
#elif ENABLED(PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA) && DISABLED(PRUSA_AIO_HOTEND_E3D_REVO_MICRO)
  #error "Bear Extruder V2 requires PRUSA_AIO_HOTEND_E3D_REVO_MICRO."
#elif ANY(PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH) && NONE(PRUSA_AIO_HOTEND_E3D_V6, PRUSA_AIO_HOTEND_E3D_REVO_SIX)
  #error "Bear Extruder V1 requires PRUSA_AIO_HOTEND_E3D_V6 or PRUSA_AIO_HOTEND_E3D_REVO_SIX."
#elif ANY(PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH) && ENABLED(PRUSA_AIO_HOTEND_E3D_V6, PRUSA_AIO_HOTEND_E3D_REVO_SIX, PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
  #error "BMG Extruder requires PRUSA_AIO_HOTEND_E3D_V6, PRUSA_AIO_HOTEND_E3D_REVO_SIX, or PRUSA_AIO_HOTEND_SLICE_MOSQUITO."
#elif ENABLED(PRUSA_AIO_EXTRUDER_SFP_PINDA) && DISABLED(PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
  #error "SFP Extruder requires PRUSA_AIO_HOTEND_SLICE_MOSQUITO."
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

#if MANY(PRUSA_AIO_HOTEND_E3D_V6, PRUSA_AIO_HOTEND_E3D_REVO_SIX, PRUSA_AIO_HOTEND_E3D_REVO_MICRO, PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
  #error "Only one PRUSA_AIO_HOTEND option can be enabled at a time."
#elif NONE(PRUSA_AIO_HOTEND_E3D_V6, PRUSA_AIO_HOTEND_E3D_REVO_SIX, PRUSA_AIO_HOTEND_E3D_REVO_MICRO, PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
  #error "Invalid PRUSA_AIO_HOTEND option."
#elif ENABLED(PRUSA_AIO_HOTEND_E3D_REVO_MICRO) && DISABLED(PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA)
  #error "PRUSA_AIO_HOTEND_E3D_REVO_MICRO is only compatible with PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA."
#elif ENABLED(PRUSA_AIO_HOTEND_SLICE_MOSQUITO) && NONE(PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH, PRUSA_AIO_EXTRUDER_SFP_PINDA)
  #error "PRUSA_AIO_HOTEND_SLICE_MOSQUITO is only compatible with PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH, or PRUSA_AIO_EXTRUDER_SFP_PINDA."
#endif

// Thermistors
#if MANY(PRUSA_AIO_THERMISTOR_SEMITEC_104NT, PRUSA_AIO_THERMISTOR_GENERIC_100K, PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_TL_T_D500)
  #error "Only one PRUSA_AIO_THERMISTOR option can be enabled at a time."
#elif NONE(PRUSA_AIO_THERMISTOR_SEMITEC_104NT, PRUSA_AIO_THERMISTOR_GENERIC_100K, PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_TL_T_D500)
  #error "Invalid PRUSA_AIO_THERMISTOR option."
#elif ANY(PRUSA_AIO_HOTEND_E3D_REVO_SIX, PRUSA_AIO_HOTEND_E3D_REVO_MICRO) && DISABLED(PRUSA_AIO_THERMISTOR_SEMITEC_104NT)
  #error "PRUSA_AIO_HOTEND_E3D_REVO option requires PRUSA_AIO_THERMISTOR_SEMITEC_104NT."
#endif

//===========================================================================
//=========================== PID / MPC Settings ============================
//===========================================================================

#if ENABLED(PRUSA_AIO_CUSTOM_HOTEND_PID)
  #ifndef PRUSA_AIO_DEFAULT_Kp
    #error "PRUSA_AIO_DEFAULT_Kp is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_DEFAULT_Ki
    #error "PRUSA_AIO_DEFAULT_Ki is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_DEFAULT_Kd
    #error "PRUSA_AIO_DEFAULT_Kd is invalid or not defined."
  #endif
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_BED_PID)
  #ifndef PRUSA_AIO_DEFAULT_bedKp
    #error "PRUSA_AIO_DEFAULT_bedKp is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_DEFAULT_bedKi
    #error "PRUSA_AIO_DEFAULT_bedKi is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_DEFAULT_bedKd
    #error "PRUSA_AIO_DEFAULT_bedKd is invalid or not defined."
  #endif
#endif

#if ALL(PRUSA_AIO_HOTEND_MPCTEMP, PRUSA_AIO_CUSTOM_HOTEND_PID)
  #error "PRUSA_AIO_HOTEND_MPCTEMP and PRUSA_AIO_CUSTOM_HOTEND_PID cannot be enabled at the same time."
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_HOTEND_MPCTEMP)
  #if DISABLED(PRUSA_AIO_HOTEND_MPCTEMP)
    #error "PRUSA_AIO_CUSTOM_HOTEND_MPCTEMP requires PRUSA_AIO_HOTEND_MPCTEMP."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_MPC_HEATER_POWER
    #error "PRUSA_AIO_CUSTOM_MPC_HEATER_POWER is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY
    #error "PRUSA_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS
    #error "PRUSA_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF
    #error "PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255
    #error "PRUSA_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM
    #error "PRUSA_AIO_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM is invalid or not defined."
  #endif
#endif

//===========================================================================
//============================ Part Cooling Fan =============================
//===========================================================================

#if MANY(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_12V_STOCK_PRUSA_MK25S_5015, PRUSA_AIO_PART_COOLING_FAN_12V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Only one PRUSA_AIO_PART_COOLING_FAN option can be enabled at a time."
#elif NONE(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_12V_STOCK_PRUSA_MK25S_5015, PRUSA_AIO_PART_COOLING_FAN_12V_SOUNDORIGINAL, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option."
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002) && NONE(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option. Only 5V fans are supported on BigTreeTech BTT002 1.0."
#elif NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_BTT002) && ANY(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option. 5V fans are for BigTreeTech BTT002 1.0 & SKR V3/EZ with DC Mode addon board only."
#elif ENABLED(PRUSA_AIO_MK25S_SUPPORT) && NONE(PRUSA_AIO_PART_COOLING_FAN_GENERIC, PRUSA_AIO_PART_COOLING_FAN_12V_STOCK_PRUSA_MK25S_5015, PRUSA_AIO_PART_COOLING_FAN_12V_SOUNDORIGINAL)
  #error "Invalid PRUSA_AIO_PART_COOLING_FAN option. PRUSA_AIO_MK25S_SUPPORT requires 12V fans."
#endif

//===========================================================================
//================================== Probe ==================================
//===========================================================================

#if MANY(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2, PRUSA_AIO_PROBE_BLTOUCH)
  #error "Only one PRUSA_AIO_PROBE option can be enabled at a time."
#elif NONE(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2, PRUSA_AIO_PROBE_BLTOUCH)
  #error "Invalid PRUSA_AIO_PROBE option."
#elif ANY(PRUSA_AIO_EXTRUDER_BEAR_V1_PINDA, PRUSA_AIO_EXTRUDER_BEAR_V2_PINDA, PRUSA_AIO_EXTRUDER_BMG_PINDA, PRUSA_AIO_EXTRUDER_SFP_PINDA) && ENABLED(PRUSA_AIO_PROBE_BLTOUCH)
  #error "Enabled PRUSA_AIO_EXTRUDER option requires PRUSA_AIO_PROBE_SUPERPINDA or PRUSA_AIO_PROBE_PINDA_V2."
#elif ANY(PRUSA_AIO_EXTRUDER_BEAR_V1_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH) && ANY(PRUSA_AIO_PROBE_SUPERPINDA, PRUSA_AIO_PROBE_PINDA_V2)
  #error "Enabled PRUSA_AIO_EXTRUDER option requires PRUSA_AIO_PROBE_BLTOUCH."
#endif

// PINDA V2 Sanity Checks
#if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1) && ENABLED(PRUSA_AIO_PROBE_PINDA_V2)
  #error "PINDA V2 is not supported on enabled motherboard. A SuperPINDA or BLTouch is required."
#endif

// No dedicated probe port
#if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0) && DISABLED(PRUSA_AIO_PROBE_USES_Z_MIN_ENDSTOP_PIN)
  #error "PRUSA_AIO_PROBE_USES_Z_MIN_ENDSTOP_PIN is required for enabled motherboard. No dedicated probe port available."
#endif

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

#if ALL(PRUSA_AIO_BED_LEVELING_BILINEAR, PRUSA_AIO_BED_LEVELING_UBL)
  #error "Only one PRUSA_AIO_BED_LEVELING option can be enabled at a time."
#elif NONE(PRUSA_AIO_BED_LEVELING_BILINEAR, PRUSA_AIO_BED_LEVELING_UBL)
  #error "Invalid PRUSA_AIO_BED_LEVELING option."
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if MANY(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_BTT_TFT35_SPI_V1, PRUSA_AIO_DISPLAY_MKS_TS35_V2_0)
  #error "Only one PRUSA_AIO_DISPLAY option can be enabled at a time."
#elif NONE(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_BTT_TFT35_SPI_V1, PRUSA_AIO_DISPLAY_MKS_TS35_V2_0)
  #error "Invalid PRUSA_AIO_DISPLAY option."
#elif ENABLED(PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER) && NONE(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
  #error "OLED RepRapDiscount smart controller is only compatible with LPC-based motherboards."
#elif ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0) && DISABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
  #error "Invalid PRUSA_AIO_DISPLAY option. SKR Mini E3 has a single EXP connector and is only compatible with PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT."
#endif

#if ANY(PRUSA_AIO_DISPLAY_BTT_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_FYSETC_MINI_12864_NEOPIXEL, PRUSA_AIO_DISPLAY_MKS_MINI_12864_NEOPIXEL)
  #if MANY(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED, PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW, PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN, PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO, PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET, PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #error "Only one PRUSA_AIO_LCD_NEOPIXEL_COLOR option can be enabled at a time."
  #elif NONE(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED, PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW, PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN, PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE, PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO, PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET, PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #error "Invalid PRUSA_AIO_LCD_NEOPIXEL_COLOR option."
  #endif
#endif

#ifndef PRUSA_AIO_LCD_LANGUAGE
  #error "Invalid PRUSA_AIO_LCD_LANGUAGE option."
#endif

//===========================================================================
//=========================== Sheet Profiles Menu ===========================
//===========================================================================

#if ENABLED(PRUSA_AIO_SHEET_PROFILES_MENU)
  // Description is enabled, but no offset
  #if defined(PRUSA_AIO_SHEET_1_DESC) && !defined(PRUSA_AIO_SHEET_1_OFFSET)
    #error "PRUSA_AIO_SHEET_1_OFFSET is required when PRUSA_AIO_SHEET_1_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_2_DESC) && !defined(PRUSA_AIO_SHEET_2_OFFSET)
    #error "PRUSA_AIO_SHEET_2_OFFSET is required when PRUSA_AIO_SHEET_2_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_3_DESC) && !defined(PRUSA_AIO_SHEET_3_OFFSET)
    #error "PRUSA_AIO_SHEET_3_OFFSET is required when PRUSA_AIO_SHEET_3_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_4_DESC) && !defined(PRUSA_AIO_SHEET_4_OFFSET)
    #error "PRUSA_AIO_SHEET_4_OFFSET is required when PRUSA_AIO_SHEET_4_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_5_DESC) && !defined(PRUSA_AIO_SHEET_5_OFFSET)
    #error "PRUSA_AIO_SHEET_5_OFFSET is required when PRUSA_AIO_SHEET_5_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_6_DESC) && !defined(PRUSA_AIO_SHEET_6_OFFSET)
    #error "PRUSA_AIO_SHEET_6_OFFSET is required when PRUSA_AIO_SHEET_6_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_7_DESC) && !defined(PRUSA_AIO_SHEET_7_OFFSET)
    #error "PRUSA_AIO_SHEET_7_OFFSET is required when PRUSA_AIO_SHEET_7_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_8_DESC) && !defined(PRUSA_AIO_SHEET_8_OFFSET)
    #error "PRUSA_AIO_SHEET_8_OFFSET is required when PRUSA_AIO_SHEET_8_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_9_DESC) && !defined(PRUSA_AIO_SHEET_9_OFFSET)
    #error "PRUSA_AIO_SHEET_9_OFFSET is required when PRUSA_AIO_SHEET_9_DESC is enabled."
  #elif defined(PRUSA_AIO_SHEET_10_DESC) && !defined(PRUSA_AIO_SHEET_10_OFFSET)
    #error "PRUSA_AIO_SHEET_10_OFFSET is required when PRUSA_AIO_SHEET_10_DESC is enabled."
  #endif

  // Offset is enabled, but no description
  #if defined(PRUSA_AIO_SHEET_1_OFFSET) && !defined(PRUSA_AIO_SHEET_1_DESC)
    #error "PRUSA_AIO_SHEET_1_DESC is required when PRUSA_AIO_SHEET_1_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_2_OFFSET) && !defined(PRUSA_AIO_SHEET_2_DESC)
    #error "PRUSA_AIO_SHEET_2_DESC is required when PRUSA_AIO_SHEET_2_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_3_OFFSET) && !defined(PRUSA_AIO_SHEET_3_DESC)
    #error "PRUSA_AIO_SHEET_3_DESC is required when PRUSA_AIO_SHEET_3_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_4_OFFSET) && !defined(PRUSA_AIO_SHEET_4_DESC)
    #error "PRUSA_AIO_SHEET_4_DESC is required when PRUSA_AIO_SHEET_4_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_5_OFFSET) && !defined(PRUSA_AIO_SHEET_5_DESC)
    #error "PRUSA_AIO_SHEET_5_DESC is required when PRUSA_AIO_SHEET_5_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_6_OFFSET) && !defined(PRUSA_AIO_SHEET_6_DESC)
    #error "PRUSA_AIO_SHEET_6_DESC is required when PRUSA_AIO_SHEET_6_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_7_OFFSET) && !defined(PRUSA_AIO_SHEET_7_DESC)
    #error "PRUSA_AIO_SHEET_7_DESC is required when PRUSA_AIO_SHEET_7_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_8_OFFSET) && !defined(PRUSA_AIO_SHEET_8_DESC)
    #error "PRUSA_AIO_SHEET_8_DESC is required when PRUSA_AIO_SHEET_8_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_9_OFFSET) && !defined(PRUSA_AIO_SHEET_9_DESC)
    #error "PRUSA_AIO_SHEET_9_DESC is required when PRUSA_AIO_SHEET_9_OFFSET is enabled."
  #elif defined(PRUSA_AIO_SHEET_10_OFFSET) && !defined(PRUSA_AIO_SHEET_10_DESC)
    #error "PRUSA_AIO_SHEET_10_DESC is required when PRUSA_AIO_SHEET_10_OFFSET is enabled."
  #endif
#endif

//===========================================================================
//============================= NeoPixel Strip ==============================
//===========================================================================

#if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP)

  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_3, PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3_1, PRUSA_AIO_MOTHERBOARD_MKS_EAGLE_V1_0)
    #error "PRUSA_AIO_NEOPIXEL_STRIP is not compatible with enabled motherboard. No dedicated NeoPixels pin available."
  #endif

  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_TYPE
    #error "PRUSA_AIO_NEOPIXEL_STRIP_TYPE is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT
    #error "PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS
    #error "PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS is invalid or not defined."
  #endif

  #if MANY(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #error "Only one PRUSA_AIO_NEOPIXEL_STRIP_COLOR option can be enabled at a time."
  #elif NONE(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO, PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #error "Invalid PRUSA_AIO_NEOPIXEL_STRIP_COLOR option."
  #endif
#endif

//===========================================================================
//============================== Input Shaping ==============================
//===========================================================================

#if ENABLED(PRUSA_AIO_INPUT_SHAPING)
  #ifndef PRUSA_AIO_SHAPING_FREQ_X
    #error "PRUSA_AIO_SHAPING_FREQ_X is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_SHAPING_FREQ_Y
    #error "PRUSA_AIO_SHAPING_FREQ_Y is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_SHAPING_ZETA_X
    #error "PRUSA_AIO_SHAPING_ZETA_X is invalid or not defined."
  #endif
  #ifndef PRUSA_AIO_SHAPING_ZETA_Y
    #error "PRUSA_AIO_SHAPING_ZETA_Y is invalid or not defined."
  #endif
#endif
