#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

#define CONFIGURATION_H_VERSION 02010100
#define PRUSA_AIO_VERSION 20220807

//===========================================================================
//================================ Warnings ================================
//===========================================================================

//#define NO_PRUSA_AIO_WARNINGS            // Prusa AIO config warnings
#define NO_AUTO_ASSIGN_WARNING             // Auto-assigned Z2 warning

//===========================================================================
//============================ Source Code Info =============================
//===========================================================================

#define SOURCE_CODE_URL "bit.ly/3FnRN20"
#define WEBSITE_URL SOURCE_CODE_URL

//===========================================================================
//============================== Printer Name ===============================
//===========================================================================

#ifndef PRUSA_AIO_CUSTOM_PRINTER_NAME
  #define PRUSA_AIO_CUSTOM_PRINTER_NAME "AIO Bear"
#endif

//===========================================================================
//=========================== Printer/Frame Type ============================
//===========================================================================

#if ENABLED(PRUSA_AIO_FRAME_BEAR_210)
  #define PRUSA_AIO_Z_MAX_POS 210
#elif ENABLED(PRUSA_AIO_FRAME_BEAR_320)
  #define PRUSA_AIO_Z_MAX_POS 320
#endif

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

// Define MOTHERBOARD here to keep preflight-checks.py "Build environment '...' is incompatible with BOARD_.... Use one of these: " script working
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ)
  #define MOTHERBOARD BOARD_BTT_SKR_V3_0_EZ
  // Features
  #define PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0)
  #define MOTHERBOARD BOARD_BTT_SKR_V3_0
  // Features
  #define PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
  #define MOTHERBOARD BOARD_BTT_SKR_V2_0_REV_B
  // Features
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO)
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
  // Features
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4)
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4
  // Features
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #define MOTHERBOARD BOARD_BTT_BTT002_V1_0
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0
  // Features
  #define PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3)
  #define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3
  // Features
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
  #define MOTHERBOARD BOARD_MKS_SGEN_L_V2
  // Features
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_DUAL_Z 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3
  // Features
  #define PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3_V1_1
  // Features
  #define PRUSA_AIO_BOARD_NO_UART_SPI_JUMPERS 1
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3D
  // Features
  #define PRUSA_AIO_NO_FAN1_PIN 1
#elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
  #define MOTHERBOARD BOARD_MKS_ROBIN_E3D_V1_1
  // Features
  #define PRUSA_AIO_REAL_EEPROM 1
  #define PRUSA_AIO_NO_FAN1_PIN 1
#endif

#define SPEAKER // Need to test on Robin E3 boards

#if ENABLED(PRUSA_AIO_FLASH_DRIVE_SUPPORT)
  #define USB_FLASH_DRIVE_SUPPORT
  //#define MULTI_VOLUME // Needs work
#endif

// Print Counter works best on boards with real EEPROMs.
#if ENABLED(PRUSA_AIO_REAL_EEPROM)
  #define PRINTCOUNTER
#endif

#if ENABLED(PRUSA_AIO_DUAL_Z)
  #define SDCARD_CONNECTION LCD
  #define SD_CHECK_AND_RETRY
  #define Z2_DRIVER_TYPE Z_DRIVER_TYPE
  #define Z_STEPPER_AUTO_ALIGN

  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4, PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2)
    #define SERIAL_PORT 0
    #define SERIAL_PORT_2 -1
  #elif ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
    #define FAN_SOFT_PWM
    #define SERIAL_PORT 1
    #define SERIAL_PORT_2 -1
  #elif ENABLED(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_NANO_V3)
    #define FAN_SOFT_PWM
    #define SERIAL_PORT -1
    #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
  #endif
#else // Single Z driver
  #define MECHANICAL_GANTRY_CALIBRATION
  #define FAN_SOFT_PWM

  #if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
    #define MK3_FAN_PINS          // Disable this for FAN_PIN PB9 and FAN1_PIN PB8
    #define SERIAL_PORT 3
    #define SERIAL_PORT_2 -1
    #define SDCARD_CONNECTION LCD // No onboard SD card reader
  #elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)
    #define SERIAL_PORT 2
    #define SERIAL_PORT_2 -1
    #define SDCARD_CONNECTION ONBOARD
  #elif ANY(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #undef SPEAKER // Need to test on Robin E3 boards
    #define SERIAL_PORT 1
    //#define SERIAL_PORT_2 2
    #define SDCARD_CONNECTION ONBOARD // SD pins are shared between ONBOARD & LCD/EXP pins
  #endif
#endif

//===========================================================================
//============================= Stepper Drivers =============================
//===========================================================================

#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #define PRUSA_AIO_DRIVER_TYPE TMC5160
  #define PRUSA_AIO_XY_ENDSTOP_INVERTING true
  #define PRUSA_AIO_DRIVER_RSENSE 0.075
  #define TMC_USE_SW_SPI
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
  #define PRUSA_AIO_DRIVER_TYPE TMC2209
  #define PRUSA_AIO_XY_ENDSTOP_INVERTING false
  #define PRUSA_AIO_DRIVER_RSENSE 0.11
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

#if DISABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)  // Adaptive Step Smoothing can cause leveling issues on BTT_SKR_MINI_E3_V3
  #define ADAPTIVE_STEP_SMOOTHING
#endif

// Default Extruder inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_E0_DIR true
  #else
    #define INVERT_E0_DIR  false
  #endif
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_E0_DIR false
  #else
    #define INVERT_E0_DIR true
  #endif
#endif

#if ENABLED(PRUSA_AIO_E_STEPPER_STOCK)
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 280
  #define E0_CURRENT                        550
  #define E0_MICROSTEPS                      32
  #define CHOPPER_TIMING_E  CHOPPER_DEFAULT_24V
#elif ENABLED(PRUSA_AIO_E_STEPPER_BONDTECH_MOTECH)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 830
  #define E0_CURRENT                        550
  #define E0_MICROSTEPS                      32
  #define CHOPPER_TIMING_E  CHOPPER_DEFAULT_24V
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_0_9)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 830
  #define E0_CURRENT                        550
  #define E0_MICROSTEPS                     16
  #define CHOPPER_TIMING_E  CHOPPER_09STEP_24V
#elif ENABLED(PRUSA_AIO_E_STEPPER_LDO_PLANETARY)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
  #define PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT 980
  #define E0_CURRENT                        650
  #define E0_MICROSTEPS                      32
  #define CHOPPER_TIMING_E  CHOPPER_DEFAULT_24V
#endif

// User Extruder inverting
#if ENABLED(PRUSA_AIO_INVERT_E_DIR)
  #if INVERT_E0_DIR == true
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR false
  #elif INVERT_E0_DIR == false
    #undef INVERT_E0_DIR  // Prevent redefined warnings
    #define INVERT_E0_DIR true
  #endif
#endif

#if ENABLED(PRUSA_AIO_XY_STEPPERS_STOCK)
  #define DEFAULT_AXIS_STEPS_PER_UNIT  { 100, 100, 400, (PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT) }

  #define CHOPPER_TIMING_X CHOPPER_DEFAULT_24V
  #define CHOPPER_TIMING_Y CHOPPER_DEFAULT_24V

  #define X_CURRENT      500
  #define X_CURRENT_HOME 200
  #define Y_CURRENT      600
  #define Y_CURRENT_HOME 250

  // StallGuard settings
  #ifdef PRUSA_AIO_X_STALL_SENSITIVITY
    #define X_STALL_SENSITIVITY PRUSA_AIO_X_STALL_SENSITIVITY
  #else
    #if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
      #define X_STALL_SENSITIVITY 2
    #elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
      #define X_STALL_SENSITIVITY 90
    #endif
  #endif
  #ifdef PRUSA_AIO_Y_STALL_SENSITIVITY
    #define Y_STALL_SENSITIVITY PRUSA_AIO_Y_STALL_SENSITIVITY
  #else
    #if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
      #define Y_STALL_SENSITIVITY 3
    #elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
      #define Y_STALL_SENSITIVITY 100
    #endif
  #endif

#elif EITHER(PRUSA_AIO_XY_STEPPERS_LDO_0_9, PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
  #define DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 400, (PRUSA_AIO_EXTRUDER_STEPS_PER_UNIT) }

  #define CHOPPER_TIMING_X CHOPPER_09STEP_24V
  #define CHOPPER_TIMING_Y CHOPPER_09STEP_24V

  #if ENABLED(PRUSA_AIO_XY_STEPPERS_LDO_0_9)
    #define X_CURRENT      900
    #define X_CURRENT_HOME 300
    #define Y_CURRENT     1000
    #define Y_CURRENT_HOME 400

    // StallGuard settings
    #ifdef PRUSA_AIO_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY PRUSA_AIO_X_STALL_SENSITIVITY
    #else
      #define X_STALL_SENSITIVITY 81
    #endif

    #ifdef PRUSA_AIO_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY PRUSA_AIO_Y_STALL_SENSITIVITY
    #else
      #define Y_STALL_SENSITIVITY 85
    #endif

  #elif ENABLED(PRUSA_AIO_XY_STEPPERS_MOONS_0_9)
    #define X_CURRENT      650
    #define X_CURRENT_HOME 225
    #define Y_CURRENT      750
    #define Y_CURRENT_HOME 200

    // StallGuard settings
    #ifdef PRUSA_AIO_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY PRUSA_AIO_X_STALL_SENSITIVITY
    #else
      #define X_STALL_SENSITIVITY 140
    #endif
    #ifdef PRUSA_AIO_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY PRUSA_AIO_Y_STALL_SENSITIVITY
    #else
      #define Y_STALL_SENSITIVITY 132
    #endif
  #endif
#endif

// Homing speeds (mm/min)
#ifndef PRUSA_AIO_HOMING_FEEDRATE_MM_M
  #define HOMING_FEEDRATE_MM_M { (50*60), (50*60), (4*60) }
#else
  #define HOMING_FEEDRATE_MM_M PRUSA_AIO_HOMING_FEEDRATE_MM_M
#endif

// Default X/Y inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if NONE(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_X_DIR  true
    #define INVERT_Y_DIR false
  #else
    #define INVERT_X_DIR false
    #define INVERT_Y_DIR  true
  #endif
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
  #if NONE(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_X_DIR false
    #define INVERT_Y_DIR  true
  #else
    #define INVERT_X_DIR  true
    #define INVERT_Y_DIR false
  #endif
#endif

// Default Z inverting
#if ENABLED(PRUSA_AIO_DRIVERS_TMC5160)
  #if NONE(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_Z_DIR  true
  #else
    #define INVERT_Z_DIR false
  #endif
#elif ENABLED(PRUSA_AIO_DRIVERS_TMC2209)
  #if NONE(PRUSA_AIO_MOTHERBOARD_BTT_BTT002, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define INVERT_Z_DIR false
  #else
    #define INVERT_Z_DIR  true
  #endif
#endif

// User X inverting
#if ENABLED(PRUSA_AIO_INVERT_X_DIR)
  #if INVERT_X_DIR == true
    #undef INVERT_X_DIR // Prevent redefined warnings
    #define INVERT_X_DIR false
  #elif INVERT_X_DIR == false
    #undef INVERT_X_DIR // Prevent redefined warnings
    #define INVERT_X_DIR true
  #endif
#endif

// User Y inverting
#if ENABLED(PRUSA_AIO_INVERT_Y_DIR)
  #if INVERT_Y_DIR == true
    #undef INVERT_Y_DIR // Prevent redefined warnings
    #define INVERT_Y_DIR false
  #elif INVERT_Y_DIR == false
    #undef INVERT_Y_DIR // Prevent redefined warnings
    #define INVERT_Y_DIR true
  #endif
#endif

// User Z inverting
#if ENABLED(PRUSA_AIO_INVERT_Z_DIR)
  #if INVERT_Z_DIR == true
    #undef INVERT_Z_DIR // Prevent redefined warnings
    #define INVERT_Z_DIR false
  #elif INVERT_Z_DIR == false
    #undef INVERT_Z_DIR // Prevent redefined warnings
    #define INVERT_Z_DIR true
  #endif
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

// E3D Hemera   Note: Shift bed to the left 11mm // X_MIN_POS -11   Y_MIN_POS -2

// Probe Temperature Compensation
#define PTC_BED        // Compensate based on bed temperature

#if EITHER(PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH, PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
  #define BLTOUCH
  #define TEMP_SENSOR_PROBE          0
  #define PROBING_MARGIN             5
  #define Z_CLEARANCE_DEPLOY_PROBE   5
  #define Z_CLEARANCE_BETWEEN_PROBES 3
  #define Z_CLEARANCE_MULTI_PROBE    3
  //#define Z_STEPPER_ALIGN_XY { { 10, 105 }, { 220, 105 } }    // Use default locations?

  #ifdef PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
  #elif ENABLED(PRUSA_AIO_EXTRUDER_BEAR_BLTOUCH)
    #define NOZZLE_TO_PROBE_OFFSET { 26.71, 2.298, 0 } // Offsets pulled from https://www.thingiverse.com/thing:3251530/comments#comment-2915938
  #elif ENABLED(PRUSA_AIO_EXTRUDER_BMG_BLTOUCH)
    #define NOZZLE_TO_PROBE_OFFSET { -24.3, -34.1, 0 } // Offsets pulled from https://www.thingiverse.com/thing:3864666/comments#comment-2882122
  #endif

#elif EITHER(PRUSA_AIO_EXTRUDER_BEAR_PINDA, PRUSA_AIO_EXTRUDER_BMG_PINDA)
  #define FIX_MOUNTED_PROBE
  #define PROBING_MARGIN             10
  #define Z_CLEARANCE_DEPLOY_PROBE    0
  #define Z_CLEARANCE_BETWEEN_PROBES  2
  #define Z_CLEARANCE_MULTI_PROBE     2
  #define PROBING_HEATERS_OFF
  #define Z_STEPPER_ALIGN_XY { { 40, 90 }, { 230, 90 } }

  #ifdef PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_AIO_NOZZLE_TO_PROBE_OFFSET
  #else
    #define NOZZLE_TO_PROBE_OFFSET { 23, 5, 0 }
  #endif

  // Probe Temperature Compensation
  #if ENABLED(PRUSA_AIO_PROBE_SUPERPINDA)
    #define TEMP_SENSOR_PROBE 0
  #elif ENABLED(PRUSA_AIO_PROBE_PINDA_V2)
    #define TEMP_SENSOR_PROBE 1
    #define PTC_PROBE    // Compensate based on probe temperature
  #endif
#endif

// Hotend Cooling Fan
// PIN_EXISTS(FAN1) doesn't work here
#if ENABLED(PRUSA_AIO_NO_FAN1_PIN)
  #define E0_AUTO_FAN_PIN -1
#else
  #define E0_AUTO_FAN_PIN FAN1_PIN
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#if ENABLED(PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT)
  #define TEMP_SENSOR_0   5
  #define HEATER_0_MAXTEMP 310 // 295 + 15
#elif ENABLED(PRUSA_AIO_THERMISTOR_GENERIC_100K)
  #define TEMP_SENSOR_0   1
  #define HEATER_0_MAXTEMP 310 // 295 + 15
#elif ENABLED(PRUSA_AIO_THERMISTOR_SLICE_450C)
  #define TEMP_SENSOR_0  67
  #define HEATER_0_MAXTEMP 465 // 450 + 15
#elif ENABLED(PRUSA_AIO_THERMISTOR_DYZE_DESIGN)
  #define TEMP_SENSOR_0  66
  #define HEATER_0_MAXTEMP 515 // 500 + 15
  #define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 5
  #define MILLISECONDS_PREHEAT_TIME 30000
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_HOTEND_PID)
  #define DEFAULT_Kp PRUSA_AIO_DEFAULT_Kp
  #define DEFAULT_Ki PRUSA_AIO_DEFAULT_Ki
  #define DEFAULT_Kd PRUSA_AIO_DEFAULT_Kd
#else
  #define DEFAULT_Kp  16.50
  #define DEFAULT_Ki   1.16
  #define DEFAULT_Kd  58.80
#endif

#if ENABLED(PRUSA_AIO_CUSTOM_BED_PID)
  #define DEFAULT_bedKp PRUSA_AIO_DEFAULT_bedKp
  #define DEFAULT_bedKi PRUSA_AIO_DEFAULT_bedKi
  #define DEFAULT_bedKd PRUSA_AIO_DEFAULT_bedKd
#else
  #define DEFAULT_bedKp  28.13
  #define DEFAULT_bedKi   2.09
  #define DEFAULT_bedKd 483.07
#endif

//===========================================================================
//============================ Part Cooling Fan =============================
//===========================================================================

// :[0,1,2,3,4,5,6,7]
#define SOFT_PWM_SCALE 1
#define SOFT_PWM_DITHER

//TODO: Test all fan/board combos
#if ENABLED(PRUSA_AIO_PART_COOLING_FAN_GENERIC)
  #define FAN_MIN_PWM 0
#elif EITHER(PRUSA_AIO_PART_COOLING_FAN_24V_MECHATRONICS_B5015E24B_BSR, PRUSA_AIO_PART_COOLING_FAN_24V_SOUNDORIGINAL)
  #if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
    #define FAN_MIN_PWM 40
  #elif ANY(PRUSA_AIO_MOTHERBOARD_MKS_SGEN_L_V2, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4)
    #define FAN_MIN_PWM 115
  #elif ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define FAN_MIN_PWM 50
  #else
    #define FAN_MIN_PWM 80
  #endif
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_24V_DELTA_BFB0524HH)
  #define FAN_MIN_PWM 20
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #define FAN_MIN_PWM 51
#elif ENABLED(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_5015)
  #define FAN_MIN_PWM 0 // TODO: Find correct value
#endif

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

#if ENABLED(PRUSA_AIO_BED_LEVELING_BILINEAR)
  #define AUTO_BED_LEVELING_BILINEAR
#elif ENABLED(PRUSA_AIO_BED_LEVELING_UBL)
  #define AUTO_BED_LEVELING_UBL
#endif

//===========================================================================
//============================= Sheet Profiles ==============================
//===========================================================================

#if ENABLED(PRUSA_AIO_SHEET_PROFILES_MENU)
  #define CUSTOM_MENU_CONFIG

  #if defined(PRUSA_AIO_SHEET_1_DESC) && defined(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_DESC PRUSA_AIO_SHEET_1_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_1_OFFSET)
    #define CONFIG_MENU_ITEM_1_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_2_DESC) && defined(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_DESC PRUSA_AIO_SHEET_2_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_2_OFFSET)
    #define CONFIG_MENU_ITEM_2_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_3_DESC) && defined(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_DESC PRUSA_AIO_SHEET_3_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_3_OFFSET)
    #define CONFIG_MENU_ITEM_3_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_4_DESC) && defined(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_DESC PRUSA_AIO_SHEET_4_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_4_OFFSET)
    #define CONFIG_MENU_ITEM_4_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_5_DESC) && defined(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_DESC PRUSA_AIO_SHEET_5_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_5_OFFSET)
    #define CONFIG_MENU_ITEM_5_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_6_DESC) && defined(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_DESC PRUSA_AIO_SHEET_6_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_6_OFFSET)
    #define CONFIG_MENU_ITEM_6_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_7_DESC) && defined(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_DESC PRUSA_AIO_SHEET_7_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_7_OFFSET)
    #define CONFIG_MENU_ITEM_7_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_8_DESC) && defined(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_DESC PRUSA_AIO_SHEET_8_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_8_OFFSET)
    #define CONFIG_MENU_ITEM_8_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_9_DESC) && defined(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_DESC PRUSA_AIO_SHEET_9_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_9_OFFSET)
    #define CONFIG_MENU_ITEM_9_CONFIRM
  #endif

  #if defined(PRUSA_AIO_SHEET_10_DESC) && defined(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_DESC PRUSA_AIO_SHEET_10_DESC ": "  STRINGIFY(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_GCODE "M851 Z" STRINGIFY(PRUSA_AIO_SHEET_10_OFFSET)
    #define CONFIG_MENU_ITEM_10_CONFIRM
  #endif

#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if EITHER(PRUSA_AIO_DISPLAY_STOCK_REPRAP_DISCOUNT_SMART_CONTROLLER, PRUSA_AIO_DISPLAY_OLED_REPRAP_DISCOUNT_SMART_CONTROLLER)
  #define REPRAP_DISCOUNT_SMART_CONTROLLER
  #define LCD_INFO_SCREEN_STYLE 1
#elif EITHER(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT, PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
  #if ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
    #if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)
      #define CR10_STOCKDISPLAY
    #else
      #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
    #endif
  #elif ENABLED(PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
    #define BTT_MINI_12864_V1
  #endif

  #if ENABLED(PRUSA_AIO_BED_LEVELING_UBL)
    #define MESH_EDIT_GFX_OVERLAY
  #endif

  #define BOOT_MARLIN_LOGO_ANIMATED
  #define BABYSTEP_ZPROBE_GFX_OVERLAY
#endif

#if ENABLED(PRUSA_AIO_REVERSE_ENCODER_DIRECTION)
  #define REVERSE_ENCODER_DIRECTION
#endif

//===========================================================================
//================================ NeoPixels ================================
//===========================================================================

#if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP) // Both NeoPixel Strip & Mini 12864 w/ NeoPixels / Dual NeoPixel workaround
  #define NEOPIXEL_LED
  #define LED_CONTROL_MENU
  #define LED_COLOR_PRESETS
  #define NEOPIXEL_STARTUP_TEST

  #define NEOPIXEL_TYPE PRUSA_AIO_NEOPIXEL_STRIP_TYPE
  #define NEOPIXEL_PIXELS PRUSA_AIO_NEOPIXEL_STRIP_LED_COUNT
  #define NEOPIXEL_BRIGHTNESS PRUSA_AIO_NEOPIXEL_STRIP_BRIGHTNESS

  #if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B)
    #define NEOPIXEL_PIN   PE6
  #elif EITHER(PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4_TURBO, PRUSA_AIO_MOTHERBOARD_BTT_SKR_1_4)
    #define NEOPIXEL_PIN P1_24
  #elif ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3)
    #define NEOPIXEL_PIN   PA8
  #elif ANY(PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3_V1_1, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D, PRUSA_AIO_MOTHERBOARD_MKS_ROBIN_E3D_V1_1)
    #define NEOPIXEL_PIN   PA2
  #endif

  #if ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_RED)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_ORANGE)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN       25
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_YELLOW)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN       75
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_GREEN)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_BLUE)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_INDIGO)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_VIOLET)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_NEOPIXEL_STRIP_COLOR_WHITE)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #endif

  #if ENABLED(PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL)
    #define NEOPIXEL2_SEPARATE
    #define NEOPIXEL2_LED
    #define NEOPIXEL2_TYPE NEO_RGB
    #define NEOPIXEL2_PIXELS 3
    #define NEOPIXEL2_BRIGHTNESS 255

    #define NEO2_COLOR_PRESETS
    #define NEOPIXEL2_PIN EXP1_06_PIN

    #if ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED)
      #define NEO2_USER_PRESET_RED        255
      #define NEO2_USER_PRESET_GREEN        0
      #define NEO2_USER_PRESET_BLUE         0
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE)
      #define NEO2_USER_PRESET_RED        255
      #define NEO2_USER_PRESET_GREEN       25
      #define NEO2_USER_PRESET_BLUE         0
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW)
      #define NEO2_USER_PRESET_RED        255
      #define NEO2_USER_PRESET_GREEN       75
      #define NEO2_USER_PRESET_BLUE         0
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN)
      #define NEO2_USER_PRESET_RED          0
      #define NEO2_USER_PRESET_GREEN      255
      #define NEO2_USER_PRESET_BLUE         0
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE)
      #define NEO2_USER_PRESET_RED          0
      #define NEO2_USER_PRESET_GREEN        0
      #define NEO2_USER_PRESET_BLUE       255
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO)
      #define NEO2_USER_PRESET_RED          0
      #define NEO2_USER_PRESET_GREEN      255
      #define NEO2_USER_PRESET_BLUE       255
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET)
      #define NEO2_USER_PRESET_RED        255
      #define NEO2_USER_PRESET_GREEN        0
      #define NEO2_USER_PRESET_BLUE       255
      #define NEO2_USER_PRESET_WHITE      255
    #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
      #define NEO2_USER_PRESET_RED        255
      #define NEO2_USER_PRESET_GREEN      255
      #define NEO2_USER_PRESET_BLUE       255
      #define NEO2_USER_PRESET_WHITE      255
    #endif
  #endif
#elif ENABLED(PRUSA_AIO_DISPLAY_MINI_12864_NEOPIXEL) // Only Mini 12864 w/ NeoPixels
  #define NEOPIXEL_LED
  #define NEOPIXEL_TYPE NEO_RGB
  #define NEOPIXEL_PIXELS 3
  #define NEOPIXEL_BRIGHTNESS 255

  #define LED_CONTROL_MENU
  #define LED_USER_PRESET_STARTUP
  #define LED_COLOR_PRESETS
  #define NEOPIXEL_PIN EXP1_06_PIN

  #if ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_RED)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_ORANGE)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN       25
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_YELLOW)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN       75
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_GREEN)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE         0
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_BLUE)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_INDIGO)
    #define LED_USER_PRESET_RED          0
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_VIOLET)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN        0
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #elif ENABLED(PRUSA_AIO_LCD_NEOPIXEL_COLOR_WHITE)
    #define LED_USER_PRESET_RED        255
    #define LED_USER_PRESET_GREEN      255
    #define LED_USER_PRESET_BLUE       255
    #define LED_USER_PRESET_WHITE      255
  #endif
#endif
