//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Prusa_AIO_Warnings.cpp
 * Test Prusa AIO configuration values and give warnings at compile-time.
 */
#include "MarlinConfig.h"
#define PRUSA_AIO_VERSION 20241019

//
// Warnings! Located here so they will appear just once in the build output.
//

/**
 * Prusa AIO Warnings / Reminders
 */
#ifndef NO_PRUSA_AIO_WARNINGS

//===========================================================================
//============================== Jumpers/Pins ===============================
//===========================================================================

#if DISABLED(PRUSA_AIO_NO_DRIVER_UART_SPI_JUMPERS)
  #if ANY(PRUSA_AIO_DRIVERS_TMC2209, PRUSA_AIO_DRIVERS_TMC2226_015_RSENSE, PRUSA_AIO_DRIVERS_TMC2226_011_RSENSE) // TMC2209s/TMC2226s are configured via UART
    #warning "Ensure driver jumpers are set to UART mode".
  #elif ANY(PRUSA_AIO_DRIVERS_TMC5160, PRUSA_AIO_DRIVERS_TMC2130) // TMC5160s/TMC2130s are configured via SPI
    #warning "Ensure driver jumpers are set to SPI mode."
  #endif
#endif

#if ENABLED(PRUSA_AIO_HAS_FIVE_DRIVERS)
  #warning "Five stepper drivers are required for enabled motherboard. E1 stepper driver will be used for Z2."
  #if ENABLED(USES_DIAG_JUMPERS)
    #if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
      #warning "DIAG jumpers must be removed for X, Y, Z, Z2 (E1), & E0 or homing and filament runout will not work correctly."
    #else
      #warning "DIAG jumpers must be installed for X & Y and removed for Z, Z2 (E1), and E0 or homing and filament runout will not work correctly."
    #endif
  #elif ENABLED(USES_DIAG_PINS)
    #if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
      #warning "DIAG pins must be cut or desoldered from X, Y, Z, Z2 (E1), and E0 drivers or homing and filament runout will not work correctly."
    #else
      #warning "DIAG pins must be cut or desoldered from Z, Z2 (E1), and E0 drivers or homing and filament runout will not work correctly."
    #endif
  #endif
#else // Four drivers
  #if ENABLED(USES_DIAG_JUMPERS)
    #if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
      #warning "DIAG jumpers must be removed for X, Y, Z, & E0 or homing and filament runout will not work correctly."
    #else
      #warning "DIAG jumpers must be installed for X & Y and removed for Z & E or homing and filament runout will not work correctly."
    #endif
  #elif ENABLED(USES_DIAG_PINS)
    #if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
      #warning "DIAG pins must be cut or desoldered from X, Y, Z, and E0 drivers or homing and filament runout will not work correctly."
    #else
      #warning "DIAG pins must be cut or desoldered from Z and E drivers or homing and filament runout will not work correctly."
    #endif
  #endif
#endif

// Remind users to check U Disk / Flash Drive jumpers since they typically ship in the WiFi position.
#if ALL(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V2_0_REV_B, PRUSA_AIO_FLASH_DRIVE_SUPPORT)
  #warning "Ensure U Disk / Flash Drive jumpers are set correctly. (See Page 12 of SKR V2's User Manual https://bit.ly/3am3PNL)"
#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

// Remind users of common LCD controller setup issues

#if ENABLED(PRUSA_AIO_DISPLAY_BTT_DUAL_MODE_TFT)
  #if ENABLED(PRUSA_AIO_SINGLE_EXP_CONNECTION)
    #warning "Connect 10-pin IDC cable from EXP1 on motherboard to EXP3 on BigTreeTech Dual Mode TFT. If LCD does not light up, try rotating EXP cable 180° on one end."
  #else
    #warning "Connect both 10-pin IDC cables from EXP1/EXP2 on motherboard to EXP1/EXP2 on BigTreeTech Dual Mode TFT. If LCD does not light up, try rotating EXP cables 180° on one end."
  #endif
#else
  #warning "If LCD does not light up, try rotating EXP cables 180° on one end."
#endif

// Remind users to remove onboard SD card after flashing or they will get a "MEDIA INIT FAIL" error message due to a shared SD_DETECT signal
#if ENABLED(PRUSA_AIO_MEDIA_INIT_WARNING)
  #warning "To prevent a 'MEDIA INIT FAIL' error message, remove onboard SD card after updating firmware."
#endif

//===========================================================================
//================================== Fans ===================================
//===========================================================================

// No FAN1_PIN available
#if ENABLED(PRUSA_AIO_NO_FAN1_PIN)
  #warning "No FAN1_PIN available for automatic hotend cooling. Connect hotend cooling fan directly to 24V power source."
#endif

// BTT002 fan pin reassignment
#if ENABLED(PRUSA_AIO_MOTHERBOARD_BTT_BTT002)
  #warning "Define MK3_FAN_PINS to swap hotend and part cooling fan pins."
#endif

// SKR V3 series with 5V fan need DC Mode board
#if ANY(PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0, PRUSA_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ) && ANY(PRUSA_AIO_PART_COOLING_FAN_5V_STOCK_PRUSA_MK3S_5015, PRUSA_AIO_PART_COOLING_FAN_5V_LDO_DF5015H05S)
  #warning "SKR 3-DC Mode addon is required to run 5V fans on SKR V3/EZ motherboards."
#endif

//===========================================================================
//============================== Temperatures ===============================
//===========================================================================

#if ANY(PRUSA_AIO_THERMISTOR_SLICE_450C, PRUSA_AIO_THERMISTOR_TL_T_D500) && DISABLED(PRUSA_AIO_HOTEND_SLICE_MOSQUITO)
  #warning "Printing above 295°C will require an upgrade from the stock V6 aluminum block or it could melt!"
#endif

//===========================================================================
//==================== MK2.5S / 12V Bed Mosfet Reminder =====================
//===========================================================================

#if ENABLED(PRUSA_AIO_MK25S_SUPPORT)
  #warning "The MK2.5S bed exceeds onboard bed mosfet rating. An external mosfet is required."
#endif

#endif // NO_PRUSA_AIO_WARNINGS

//===========================================================================
//============================== Please Donate ==============================
//===========================================================================

#warning "If you find this project helpful, please consider donating at https://github.com/sponsors/thisiskeithb or https://ko-fi.com/thisiskeithb"
